<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260312103538 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'MERC-112: Abonnement entity, UtilisateurOrganisation junction, siren on Organisation, isPrimary + siret on Etablissement, data backfill';
    }

    public function up(Schema $schema): void
    {
        $sm = $this->connection->createSchemaManager();

        // Create abonnement table
        if (!$sm->tablesExist(['abonnement'])) {
            $this->addSql('CREATE TABLE abonnement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, plan VARCHAR(20) DEFAULT \'trial\' NOT NULL, starts_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ends_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stripe_subscription_id VARCHAR(255) DEFAULT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organisation_id INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_351268BB9E6B1585 ON abonnement (organisation_id)');
            $this->addSql('ALTER TABLE abonnement ADD CONSTRAINT FK_351268BB9E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        }

        // Create utilisateur_organisation junction table
        if (!$sm->tablesExist(['utilisateur_organisation'])) {
            $this->addSql('CREATE TABLE utilisateur_organisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(20) DEFAULT \'owner\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, organisation_id INT NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_8F131647FB88E14F ON utilisateur_organisation (utilisateur_id)');
            $this->addSql('CREATE INDEX IDX_8F1316479E6B1585 ON utilisateur_organisation (organisation_id)');
            $this->addSql('CREATE UNIQUE INDEX unique_utilisateur_organisation ON utilisateur_organisation (utilisateur_id, organisation_id)');
            $this->addSql('ALTER TABLE utilisateur_organisation ADD CONSTRAINT FK_8F131647FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id)');
            $this->addSql('ALTER TABLE utilisateur_organisation ADD CONSTRAINT FK_8F1316479E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id)');
        }

        // Add siren to organisation
        $orgColumns = array_map(fn ($c) => $c->getName(), $sm->listTableColumns('organisation'));
        if (!in_array('siren', $orgColumns, true)) {
            $this->addSql('ALTER TABLE organisation ADD COLUMN siren VARCHAR(9) DEFAULT NULL');
            $this->addSql('CREATE UNIQUE INDEX UNIQ_E6E132B4DB8BBA08 ON organisation (siren)');
        }

        // Add siret and isPrimary to etablissement
        $etabColumns = array_map(fn ($c) => $c->getName(), $sm->listTableColumns('etablissement'));
        if (!in_array('siret', $etabColumns, true)) {
            $this->addSql('ALTER TABLE etablissement ADD COLUMN siret VARCHAR(14) DEFAULT NULL');
        }
        if (!in_array('is_primary', $etabColumns, true)) {
            $this->addSql('ALTER TABLE etablissement ADD COLUMN is_primary BOOLEAN DEFAULT false NOT NULL');
        }

        // Data migration: create Abonnement for each existing Organisation
        $this->addSql('INSERT INTO abonnement (organisation_id, plan, starts_at, active, created_at, updated_at) SELECT id, \'single\', NOW(), true, NOW(), NOW() FROM organisation WHERE id NOT IN (SELECT organisation_id FROM abonnement)');

        // Data migration: backfill utilisateur_organisation
        $this->addSql('INSERT INTO utilisateur_organisation (utilisateur_id, organisation_id, role, created_at) SELECT id, organisation_id, \'owner\', NOW() FROM utilisateur WHERE organisation_id IS NOT NULL AND id NOT IN (SELECT utilisateur_id FROM utilisateur_organisation)');

        // Data migration: extract SIREN from SIRET
        $this->addSql('UPDATE organisation SET siren = SUBSTRING(siret, 1, 9) WHERE siret IS NOT NULL AND LENGTH(siret) = 14 AND siren IS NULL');

        // Data migration: mark first etablissement per organisation as isPrimary
        $this->addSql('UPDATE etablissement SET is_primary = true WHERE id IN (SELECT MIN(id) FROM etablissement GROUP BY organisation_id) AND is_primary = false');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS abonnement');
        $this->addSql('DROP TABLE IF EXISTS utilisateur_organisation');
        $this->addSql('ALTER TABLE etablissement DROP COLUMN IF EXISTS siret');
        $this->addSql('ALTER TABLE etablissement DROP COLUMN IF EXISTS is_primary');
        $this->addSql('DROP INDEX IF EXISTS UNIQ_E6E132B4DB8BBA08');
        $this->addSql('ALTER TABLE organisation DROP COLUMN IF EXISTS siren');
    }
}
