<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260304140307 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'MERC-69: Create avoir_fournisseur and ligne_avoir tables';
    }

    public function up(Schema $schema): void
    {
        $this->skipIf(
            $this->connection->createSchemaManager()->tablesExist(['avoir_fournisseur']),
            'Table avoir_fournisseur already exists'
        );

        $this->addSql('CREATE TABLE avoir_fournisseur (id UUID NOT NULL, reference VARCHAR(50) DEFAULT NULL, statut VARCHAR(20) DEFAULT \'DEMANDE\' NOT NULL, motif VARCHAR(30) NOT NULL, montant_ht NUMERIC(12, 2) DEFAULT NULL, montant_tva NUMERIC(12, 2) DEFAULT NULL, montant_ttc NUMERIC(12, 2) DEFAULT NULL, commentaire TEXT DEFAULT NULL, demande_le TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, recu_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, impute_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fournisseur_id INT NOT NULL, etablissement_id INT NOT NULL, bon_livraison_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_avoir_fournisseur ON avoir_fournisseur (fournisseur_id)');
        $this->addSql('CREATE INDEX idx_avoir_etablissement ON avoir_fournisseur (etablissement_id)');
        $this->addSql('CREATE INDEX idx_avoir_bon_livraison ON avoir_fournisseur (bon_livraison_id)');
        $this->addSql('CREATE INDEX idx_avoir_statut ON avoir_fournisseur (statut)');
        $this->addSql('CREATE INDEX IDX_4C383676B03A8386 ON avoir_fournisseur (created_by_id)');
        $this->addSql('CREATE INDEX IDX_4C383676C69DE5E5 ON avoir_fournisseur (validated_by_id)');
        $this->addSql('CREATE TABLE ligne_avoir (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, designation VARCHAR(255) NOT NULL, quantite NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 4) NOT NULL, montant_ligne NUMERIC(12, 2) NOT NULL, avoir_id UUID NOT NULL, produit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ligne_avoir ON ligne_avoir (avoir_id)');
        $this->addSql('CREATE INDEX IDX_6637F073F347EFB ON ligne_avoir (produit_id)');
        $this->addSql('ALTER TABLE avoir_fournisseur ADD CONSTRAINT FK_4C383676670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE avoir_fournisseur ADD CONSTRAINT FK_4C383676FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
        $this->addSql('ALTER TABLE avoir_fournisseur ADD CONSTRAINT FK_4C383676D8D16068 FOREIGN KEY (bon_livraison_id) REFERENCES bon_livraison (id)');
        $this->addSql('ALTER TABLE avoir_fournisseur ADD CONSTRAINT FK_4C383676B03A8386 FOREIGN KEY (created_by_id) REFERENCES utilisateur (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE avoir_fournisseur ADD CONSTRAINT FK_4C383676C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES utilisateur (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ligne_avoir ADD CONSTRAINT FK_6637F073C36D46DB FOREIGN KEY (avoir_id) REFERENCES avoir_fournisseur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ligne_avoir ADD CONSTRAINT FK_6637F073F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ligne_avoir DROP CONSTRAINT IF EXISTS FK_6637F073C36D46DB');
        $this->addSql('ALTER TABLE ligne_avoir DROP CONSTRAINT IF EXISTS FK_6637F073F347EFB');
        $this->addSql('DROP TABLE IF EXISTS ligne_avoir');
        $this->addSql('DROP TABLE IF EXISTS avoir_fournisseur');
    }
}
