<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260313140311 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE alerte_controle (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type_alerte VARCHAR(30) NOT NULL, message VARCHAR(500) NOT NULL, valeur_attendue NUMERIC(12, 4) DEFAULT NULL, valeur_recue NUMERIC(12, 4) DEFAULT NULL, ecart_pct NUMERIC(8, 2) DEFAULT NULL, statut VARCHAR(20) DEFAULT \'NOUVELLE\' NOT NULL, commentaire TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, traitee_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, ligne_bl_id INT NOT NULL, traitee_par_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EE56732B3338F50D ON alerte_controle (traitee_par_id)');
        $this->addSql('CREATE INDEX idx_alerte_ligne ON alerte_controle (ligne_bl_id)');
        $this->addSql('CREATE INDEX idx_alerte_statut ON alerte_controle (statut)');
        $this->addSql('CREATE TABLE audit_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action VARCHAR(10) NOT NULL, entity_type VARCHAR(100) NOT NULL, entity_id INT NOT NULL, entity_label VARCHAR(255) DEFAULT NULL, changes JSON DEFAULT NULL, ip_address VARCHAR(45) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_audit_log_date ON audit_log (created_at)');
        $this->addSql('CREATE INDEX idx_audit_log_entity ON audit_log (entity_type, entity_id)');
        $this->addSql('CREATE INDEX idx_audit_log_user ON audit_log (utilisateur_id)');
        $this->addSql('CREATE TABLE bon_livraison (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, numero_bl VARCHAR(100) DEFAULT NULL, numero_commande VARCHAR(100) DEFAULT NULL, date_livraison DATE NOT NULL, statut VARCHAR(20) DEFAULT \'BROUILLON\' NOT NULL, image_path VARCHAR(500) DEFAULT NULL, donnees_brutes JSON DEFAULT NULL, total_ht NUMERIC(12, 2) DEFAULT NULL, notes TEXT DEFAULT NULL, validated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, etablissement_id INT NOT NULL, fournisseur_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_31A531A4B03A8386 ON bon_livraison (created_by_id)');
        $this->addSql('CREATE INDEX IDX_31A531A4C69DE5E5 ON bon_livraison (validated_by_id)');
        $this->addSql('CREATE INDEX idx_bl_etablissement ON bon_livraison (etablissement_id)');
        $this->addSql('CREATE INDEX idx_bl_fournisseur ON bon_livraison (fournisseur_id)');
        $this->addSql('CREATE INDEX idx_bl_date ON bon_livraison (date_livraison)');
        $this->addSql('CREATE INDEX idx_bl_statut ON bon_livraison (statut)');
        $this->addSql('CREATE TABLE categorie_produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(100) NOT NULL, code VARCHAR(50) NOT NULL, ordre INT DEFAULT 0 NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7626428577153098 ON categorie_produit (code)');
        $this->addSql('CREATE INDEX IDX_76264285727ACA70 ON categorie_produit (parent_id)');
        $this->addSql('CREATE TABLE conversion_unite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, facteur NUMERIC(15, 6) NOT NULL, unite_source_id INT NOT NULL, unite_cible_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B80E7D6811CD3824 ON conversion_unite (unite_source_id)');
        $this->addSql('CREATE INDEX IDX_B80E7D68E60BC51A ON conversion_unite (unite_cible_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_conversion ON conversion_unite (unite_source_id, unite_cible_id)');
        $this->addSql('CREATE TABLE etablissement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, adresse VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, ville VARCHAR(100) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_etablissement_organisation ON etablissement (organisation_id)');
        $this->addSql('CREATE TABLE fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, code VARCHAR(50) DEFAULT NULL, adresse VARCHAR(255) DEFAULT NULL, code_postal VARCHAR(10) DEFAULT NULL, ville VARCHAR(100) DEFAULT NULL, telephone VARCHAR(20) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, siret VARCHAR(14) DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE fournisseur_etablissement (fournisseur_id INT NOT NULL, etablissement_id INT NOT NULL, PRIMARY KEY (fournisseur_id, etablissement_id))');
        $this->addSql('CREATE INDEX IDX_A79C9BDC670C757F ON fournisseur_etablissement (fournisseur_id)');
        $this->addSql('CREATE INDEX IDX_A79C9BDCFF631228 ON fournisseur_etablissement (etablissement_id)');
        $this->addSql('CREATE TABLE ligne_bon_livraison (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_produit_bl VARCHAR(50) DEFAULT NULL, designation_bl VARCHAR(255) NOT NULL, quantite_commandee NUMERIC(10, 3) DEFAULT NULL, quantite_livree NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 4) NOT NULL, total_ligne NUMERIC(12, 4) NOT NULL, statut_controle VARCHAR(20) DEFAULT \'NON_CONTROLE\' NOT NULL, valide BOOLEAN DEFAULT false NOT NULL, ordre INT DEFAULT 0 NOT NULL, unite_livraison VARCHAR(20) DEFAULT NULL, quantite_facturee NUMERIC(12, 4) DEFAULT NULL, unite_facturation VARCHAR(20) DEFAULT NULL, majoration_decote NUMERIC(10, 4) DEFAULT NULL, code_tva VARCHAR(10) DEFAULT NULL, origine VARCHAR(10) DEFAULT NULL, numero_ligne_bl INT DEFAULT NULL, bon_livraison_id INT NOT NULL, produit_fournisseur_id INT DEFAULT NULL, unite_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AC630C5EC4A74AB ON ligne_bon_livraison (unite_id)');
        $this->addSql('CREATE INDEX idx_ligne_bl ON ligne_bon_livraison (bon_livraison_id)');
        $this->addSql('CREATE INDEX idx_ligne_produit_fournisseur ON ligne_bon_livraison (produit_fournisseur_id)');
        $this->addSql('CREATE TABLE login_log (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, ip_address VARCHAR(45) DEFAULT NULL, user_agent VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_login_log_date ON login_log (created_at)');
        $this->addSql('CREATE INDEX idx_login_log_user ON login_log (utilisateur_id)');
        $this->addSql('CREATE INDEX idx_login_log_status ON login_log (status)');
        $this->addSql('CREATE TABLE mercuriale (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, prix_negocie NUMERIC(10, 4) NOT NULL, date_debut DATE NOT NULL, date_fin DATE DEFAULT NULL, seuil_alerte_pct NUMERIC(5, 2) DEFAULT \'5.00\' NOT NULL, notes TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, produit_fournisseur_id INT NOT NULL, etablissement_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A61A64F7B03A8386 ON mercuriale (created_by_id)');
        $this->addSql('CREATE INDEX idx_mercuriale_produit_fournisseur ON mercuriale (produit_fournisseur_id)');
        $this->addSql('CREATE INDEX idx_mercuriale_etablissement ON mercuriale (etablissement_id)');
        $this->addSql('CREATE INDEX idx_mercuriale_dates ON mercuriale (date_debut, date_fin)');
        $this->addSql('CREATE TABLE mercuriale_import (id UUID NOT NULL, original_filename VARCHAR(255) NOT NULL, parsed_data JSON NOT NULL, column_mapping JSON DEFAULT NULL, preview_result JSON DEFAULT NULL, import_result JSON DEFAULT NULL, status VARCHAR(20) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, total_rows INT NOT NULL, detected_headers JSON DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fournisseur_id INT NOT NULL, created_by_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1491A97FB03A8386 ON mercuriale_import (created_by_id)');
        $this->addSql('CREATE INDEX idx_mercuriale_import_fournisseur ON mercuriale_import (fournisseur_id)');
        $this->addSql('CREATE INDEX idx_mercuriale_import_status ON mercuriale_import (status)');
        $this->addSql('CREATE INDEX idx_mercuriale_import_expires ON mercuriale_import (expires_at)');
        $this->addSql('CREATE TABLE mercuriale_import_etablissement (mercuriale_import_id UUID NOT NULL, etablissement_id INT NOT NULL, PRIMARY KEY (mercuriale_import_id, etablissement_id))');
        $this->addSql('CREATE INDEX IDX_4E820381C1214E3B ON mercuriale_import_etablissement (mercuriale_import_id)');
        $this->addSql('CREATE INDEX IDX_4E820381FF631228 ON mercuriale_import_etablissement (etablissement_id)');
        $this->addSql('CREATE TABLE organisation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, siret VARCHAR(14) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE organisation_fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_client VARCHAR(50) DEFAULT NULL, contact_commercial VARCHAR(255) DEFAULT NULL, email_commande VARCHAR(255) DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organisation_id INT NOT NULL, fournisseur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FEC176A49E6B1585 ON organisation_fournisseur (organisation_id)');
        $this->addSql('CREATE INDEX IDX_FEC176A4670C757F ON organisation_fournisseur (fournisseur_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_org_fournisseur ON organisation_fournisseur (organisation_id, fournisseur_id)');
        $this->addSql('CREATE TABLE produit (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(255) NOT NULL, code_interne VARCHAR(50) DEFAULT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, categorie_id INT DEFAULT NULL, unite_base_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_29A5EC27D30E9EE2 ON produit (unite_base_id)');
        $this->addSql('CREATE INDEX idx_produit_categorie ON produit (categorie_id)');
        $this->addSql('CREATE TABLE produit_fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code_fournisseur VARCHAR(50) NOT NULL, designation_fournisseur VARCHAR(255) NOT NULL, conditionnement NUMERIC(10, 3) DEFAULT \'1.000\' NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, produit_id INT DEFAULT NULL, fournisseur_id INT NOT NULL, unite_achat_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_48868EB6B1F04A04 ON produit_fournisseur (unite_achat_id)');
        $this->addSql('CREATE INDEX idx_produit_fournisseur_fournisseur ON produit_fournisseur (fournisseur_id)');
        $this->addSql('CREATE INDEX idx_produit_fournisseur_produit ON produit_fournisseur (produit_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_fournisseur_code ON produit_fournisseur (fournisseur_id, code_fournisseur)');
        $this->addSql('CREATE TABLE push_subscriptions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, endpoint VARCHAR(500) NOT NULL, p256dh_key VARCHAR(255) NOT NULL, auth_token VARCHAR(255) NOT NULL, user_agent VARCHAR(500) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3FEC449DC4420F7B ON push_subscriptions (endpoint)');
        $this->addSql('CREATE INDEX IDX_PUSH_UTILISATEUR ON push_subscriptions (utilisateur_id)');
        $this->addSql('CREATE TABLE refresh_tokens (refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, revoked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9BACE7E1C74F2195 ON refresh_tokens (refresh_token)');
        $this->addSql('CREATE TABLE unite (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nom VARCHAR(50) NOT NULL, code VARCHAR(10) NOT NULL, type VARCHAR(20) NOT NULL, ordre INT DEFAULT 0 NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D64C11877153098 ON unite (code)');
        $this->addSql('CREATE TABLE utilisateur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, nom VARCHAR(100) NOT NULL, prenom VARCHAR(100) NOT NULL, roles JSON NOT NULL, actif BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, organisation_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1D1C63B3E7927C74 ON utilisateur (email)');
        $this->addSql('CREATE INDEX idx_utilisateur_organisation ON utilisateur (organisation_id)');
        $this->addSql('CREATE TABLE utilisateur_etablissement (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, role VARCHAR(50) DEFAULT \'ROLE_VIEWER\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, utilisateur_id INT NOT NULL, etablissement_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_42008AEFB88E14F ON utilisateur_etablissement (utilisateur_id)');
        $this->addSql('CREATE INDEX IDX_42008AEFF631228 ON utilisateur_etablissement (etablissement_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_utilisateur_etablissement ON utilisateur_etablissement (utilisateur_id, etablissement_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE alerte_controle ADD CONSTRAINT FK_EE56732BCE8C6D99 FOREIGN KEY (ligne_bl_id) REFERENCES ligne_bon_livraison (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE alerte_controle ADD CONSTRAINT FK_EE56732B3338F50D FOREIGN KEY (traitee_par_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE audit_log ADD CONSTRAINT FK_F6E1C0F5FB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A4FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A4670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A4B03A8386 FOREIGN KEY (created_by_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bon_livraison ADD CONSTRAINT FK_31A531A4C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE categorie_produit ADD CONSTRAINT FK_76264285727ACA70 FOREIGN KEY (parent_id) REFERENCES categorie_produit (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversion_unite ADD CONSTRAINT FK_B80E7D6811CD3824 FOREIGN KEY (unite_source_id) REFERENCES unite (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE conversion_unite ADD CONSTRAINT FK_B80E7D68E60BC51A FOREIGN KEY (unite_cible_id) REFERENCES unite (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE etablissement ADD CONSTRAINT FK_20FD592C9E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE fournisseur_etablissement ADD CONSTRAINT FK_A79C9BDC670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fournisseur_etablissement ADD CONSTRAINT FK_A79C9BDCFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C5D8D16068 FOREIGN KEY (bon_livraison_id) REFERENCES bon_livraison (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C5649D40A FOREIGN KEY (produit_fournisseur_id) REFERENCES produit_fournisseur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ligne_bon_livraison ADD CONSTRAINT FK_3AC630C5EC4A74AB FOREIGN KEY (unite_id) REFERENCES unite (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE login_log ADD CONSTRAINT FK_F16D9FFFFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mercuriale ADD CONSTRAINT FK_A61A64F7649D40A FOREIGN KEY (produit_fournisseur_id) REFERENCES produit_fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mercuriale ADD CONSTRAINT FK_A61A64F7FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mercuriale ADD CONSTRAINT FK_A61A64F7B03A8386 FOREIGN KEY (created_by_id) REFERENCES utilisateur (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mercuriale_import ADD CONSTRAINT FK_1491A97F670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mercuriale_import ADD CONSTRAINT FK_1491A97FB03A8386 FOREIGN KEY (created_by_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE mercuriale_import_etablissement ADD CONSTRAINT FK_4E820381C1214E3B FOREIGN KEY (mercuriale_import_id) REFERENCES mercuriale_import (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE mercuriale_import_etablissement ADD CONSTRAINT FK_4E820381FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE organisation_fournisseur ADD CONSTRAINT FK_FEC176A49E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE organisation_fournisseur ADD CONSTRAINT FK_FEC176A4670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27BCF5E72D FOREIGN KEY (categorie_id) REFERENCES categorie_produit (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit ADD CONSTRAINT FK_29A5EC27D30E9EE2 FOREIGN KEY (unite_base_id) REFERENCES unite (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit_fournisseur ADD CONSTRAINT FK_48868EB6F347EFB FOREIGN KEY (produit_id) REFERENCES produit (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit_fournisseur ADD CONSTRAINT FK_48868EB6670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE produit_fournisseur ADD CONSTRAINT FK_48868EB6B1F04A04 FOREIGN KEY (unite_achat_id) REFERENCES unite (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE push_subscriptions ADD CONSTRAINT FK_3FEC449DFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur ADD CONSTRAINT FK_1D1C63B39E6B1585 FOREIGN KEY (organisation_id) REFERENCES organisation (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_etablissement ADD CONSTRAINT FK_42008AEFB88E14F FOREIGN KEY (utilisateur_id) REFERENCES utilisateur (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE utilisateur_etablissement ADD CONSTRAINT FK_42008AEFF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE alerte_controle DROP CONSTRAINT FK_EE56732BCE8C6D99');
        $this->addSql('ALTER TABLE alerte_controle DROP CONSTRAINT FK_EE56732B3338F50D');
        $this->addSql('ALTER TABLE audit_log DROP CONSTRAINT FK_F6E1C0F5FB88E14F');
        $this->addSql('ALTER TABLE bon_livraison DROP CONSTRAINT FK_31A531A4FF631228');
        $this->addSql('ALTER TABLE bon_livraison DROP CONSTRAINT FK_31A531A4670C757F');
        $this->addSql('ALTER TABLE bon_livraison DROP CONSTRAINT FK_31A531A4B03A8386');
        $this->addSql('ALTER TABLE bon_livraison DROP CONSTRAINT FK_31A531A4C69DE5E5');
        $this->addSql('ALTER TABLE categorie_produit DROP CONSTRAINT FK_76264285727ACA70');
        $this->addSql('ALTER TABLE conversion_unite DROP CONSTRAINT FK_B80E7D6811CD3824');
        $this->addSql('ALTER TABLE conversion_unite DROP CONSTRAINT FK_B80E7D68E60BC51A');
        $this->addSql('ALTER TABLE etablissement DROP CONSTRAINT FK_20FD592C9E6B1585');
        $this->addSql('ALTER TABLE fournisseur_etablissement DROP CONSTRAINT FK_A79C9BDC670C757F');
        $this->addSql('ALTER TABLE fournisseur_etablissement DROP CONSTRAINT FK_A79C9BDCFF631228');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP CONSTRAINT FK_3AC630C5D8D16068');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP CONSTRAINT FK_3AC630C5649D40A');
        $this->addSql('ALTER TABLE ligne_bon_livraison DROP CONSTRAINT FK_3AC630C5EC4A74AB');
        $this->addSql('ALTER TABLE login_log DROP CONSTRAINT FK_F16D9FFFFB88E14F');
        $this->addSql('ALTER TABLE mercuriale DROP CONSTRAINT FK_A61A64F7649D40A');
        $this->addSql('ALTER TABLE mercuriale DROP CONSTRAINT FK_A61A64F7FF631228');
        $this->addSql('ALTER TABLE mercuriale DROP CONSTRAINT FK_A61A64F7B03A8386');
        $this->addSql('ALTER TABLE mercuriale_import DROP CONSTRAINT FK_1491A97F670C757F');
        $this->addSql('ALTER TABLE mercuriale_import DROP CONSTRAINT FK_1491A97FB03A8386');
        $this->addSql('ALTER TABLE mercuriale_import_etablissement DROP CONSTRAINT FK_4E820381C1214E3B');
        $this->addSql('ALTER TABLE mercuriale_import_etablissement DROP CONSTRAINT FK_4E820381FF631228');
        $this->addSql('ALTER TABLE organisation_fournisseur DROP CONSTRAINT FK_FEC176A49E6B1585');
        $this->addSql('ALTER TABLE organisation_fournisseur DROP CONSTRAINT FK_FEC176A4670C757F');
        $this->addSql('ALTER TABLE produit DROP CONSTRAINT FK_29A5EC27BCF5E72D');
        $this->addSql('ALTER TABLE produit DROP CONSTRAINT FK_29A5EC27D30E9EE2');
        $this->addSql('ALTER TABLE produit_fournisseur DROP CONSTRAINT FK_48868EB6F347EFB');
        $this->addSql('ALTER TABLE produit_fournisseur DROP CONSTRAINT FK_48868EB6670C757F');
        $this->addSql('ALTER TABLE produit_fournisseur DROP CONSTRAINT FK_48868EB6B1F04A04');
        $this->addSql('ALTER TABLE push_subscriptions DROP CONSTRAINT FK_3FEC449DFB88E14F');
        $this->addSql('ALTER TABLE utilisateur DROP CONSTRAINT FK_1D1C63B39E6B1585');
        $this->addSql('ALTER TABLE utilisateur_etablissement DROP CONSTRAINT FK_42008AEFB88E14F');
        $this->addSql('ALTER TABLE utilisateur_etablissement DROP CONSTRAINT FK_42008AEFF631228');
        $this->addSql('DROP TABLE alerte_controle');
        $this->addSql('DROP TABLE audit_log');
        $this->addSql('DROP TABLE bon_livraison');
        $this->addSql('DROP TABLE categorie_produit');
        $this->addSql('DROP TABLE conversion_unite');
        $this->addSql('DROP TABLE etablissement');
        $this->addSql('DROP TABLE fournisseur');
        $this->addSql('DROP TABLE fournisseur_etablissement');
        $this->addSql('DROP TABLE ligne_bon_livraison');
        $this->addSql('DROP TABLE login_log');
        $this->addSql('DROP TABLE mercuriale');
        $this->addSql('DROP TABLE mercuriale_import');
        $this->addSql('DROP TABLE mercuriale_import_etablissement');
        $this->addSql('DROP TABLE organisation');
        $this->addSql('DROP TABLE organisation_fournisseur');
        $this->addSql('DROP TABLE produit');
        $this->addSql('DROP TABLE produit_fournisseur');
        $this->addSql('DROP TABLE push_subscriptions');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE unite');
        $this->addSql('DROP TABLE utilisateur');
        $this->addSql('DROP TABLE utilisateur_etablissement');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
