<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260304152445 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create facture_fournisseur and ligne_facture_fournisseur tables';
    }

    public function up(Schema $schema): void
    {
        $this->skipIf(
            $this->connection->createSchemaManager()->tablesExist(['facture_fournisseur']),
            'Table facture_fournisseur already exists'
        );

        $this->addSql('CREATE TABLE facture_fournisseur (id UUID NOT NULL, external_id VARCHAR(100) NOT NULL, numero_facture VARCHAR(100) NOT NULL, date_emission DATE NOT NULL, fournisseur_nom VARCHAR(255) DEFAULT NULL, fournisseur_tva VARCHAR(30) DEFAULT NULL, fournisseur_siren VARCHAR(9) DEFAULT NULL, acheteur_nom VARCHAR(255) DEFAULT NULL, acheteur_tva VARCHAR(30) DEFAULT NULL, statut VARCHAR(20) DEFAULT \'RECUE\' NOT NULL, montant_ht NUMERIC(12, 2) NOT NULL, montant_tva NUMERIC(12, 2) DEFAULT NULL, montant_ttc NUMERIC(12, 2) NOT NULL, devise VARCHAR(3) DEFAULT \'EUR\' NOT NULL, commentaire TEXT DEFAULT NULL, motif_refus TEXT DEFAULT NULL, document_original_path VARCHAR(500) DEFAULT NULL, acceptee_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, payee_le TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, fournisseur_id INT DEFAULT NULL, etablissement_id INT NOT NULL, bon_livraison_id INT DEFAULT NULL, validated_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_facture_fournisseur ON facture_fournisseur (fournisseur_id)');
        $this->addSql('CREATE INDEX idx_facture_etablissement ON facture_fournisseur (etablissement_id)');
        $this->addSql('CREATE INDEX idx_facture_statut ON facture_fournisseur (statut)');
        $this->addSql('CREATE INDEX IDX_311911C4D8D16068 ON facture_fournisseur (bon_livraison_id)');
        $this->addSql('CREATE INDEX IDX_311911C4C69DE5E5 ON facture_fournisseur (validated_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_facture_external_id ON facture_fournisseur (external_id)');
        $this->addSql('CREATE TABLE ligne_facture_fournisseur (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, external_id VARCHAR(100) DEFAULT NULL, code_article VARCHAR(50) DEFAULT NULL, designation VARCHAR(255) NOT NULL, quantite NUMERIC(10, 3) NOT NULL, prix_unitaire NUMERIC(10, 4) NOT NULL, montant_ligne NUMERIC(12, 2) NOT NULL, taux_tva NUMERIC(5, 2) DEFAULT NULL, unite VARCHAR(20) DEFAULT NULL, facture_id UUID NOT NULL, produit_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_ligne_facture ON ligne_facture_fournisseur (facture_id)');
        $this->addSql('CREATE INDEX IDX_EA175387F347EFB ON ligne_facture_fournisseur (produit_id)');
        $this->addSql('ALTER TABLE facture_fournisseur ADD CONSTRAINT FK_311911C4670C757F FOREIGN KEY (fournisseur_id) REFERENCES fournisseur (id)');
        $this->addSql('ALTER TABLE facture_fournisseur ADD CONSTRAINT FK_311911C4FF631228 FOREIGN KEY (etablissement_id) REFERENCES etablissement (id)');
        $this->addSql('ALTER TABLE facture_fournisseur ADD CONSTRAINT FK_311911C4D8D16068 FOREIGN KEY (bon_livraison_id) REFERENCES bon_livraison (id)');
        $this->addSql('ALTER TABLE facture_fournisseur ADD CONSTRAINT FK_311911C4C69DE5E5 FOREIGN KEY (validated_by_id) REFERENCES utilisateur (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE ligne_facture_fournisseur ADD CONSTRAINT FK_EA1753877F2DEE08 FOREIGN KEY (facture_id) REFERENCES facture_fournisseur (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ligne_facture_fournisseur ADD CONSTRAINT FK_EA175387F347EFB FOREIGN KEY (produit_id) REFERENCES produit_fournisseur (id) ON DELETE SET NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS ligne_facture_fournisseur');
        $this->addSql('DROP TABLE IF EXISTS facture_fournisseur');
    }
}
